create table `AgsAnnotation` (
	`id`				bigint unsigned auto_increment primary key,
	`subtype`			char(20) not null,
	`desc`				text,
	`performerId`		int unsigned not null,
	`performerIp`		char(45) not null,
	`performerName`		char(30) charset utf8 not null,
	`containerId`		int unsigned not null,
	`containerClass`	char(20) not null,
	`accessId`			tinyint not null,
	`created`			int unsigned not null,
	`updated`			int unsigned not null,
	`status`			enum('active','pending','banned') not null,
	`enabled`			bool not null,	
	
	key `subtype` (`subtype`),	
	key `performerId` (`performerId`),
	key `performerIp` (`performerIp`),
	key `performerName` (`performerName`),
	key `containerId` (`containerId`),
	key `containerClass` (`containerClass`),
	key `accessId` (`accessId`),
	key `created` (`created`),
	key `updated` (`updated`),
	key `status` (`status`),
	key `enabled` (`enabled`)
) engine = MyISAM;